### PR TITLE
Updates to support DND5e v3 character sheet

### PR DESCRIPTION
**Pull request by d20an**
Hi, this should fix the module to work with the new DND5e system v3.0.0 character sheets.

### CODE REVIEW

**Comment by jrbuda** [comment]
I manually edited my local files to reflect these changes and I am not seeing the Actions tab appear.
image
[foundryvtt-dnd5eCharacterActions.js.txt](https://github.com/eastcw/foundryvtt-dnd5eCharacterActions/files/14623319/foundryvtt-dnd5eCharacterActions.js.txt)
[actor-actions-list-v2.hbs.txt](https://github.com/eastcw/foundryvtt-dnd5eCharacterActions/files/14623320/actor-actions-list-v2.hbs.txt)
I converted the files to txt files since GitHub does not allow uploads of code files into comments

**Comment by d20an** [comment]
These changes are to support the new DND5e v3 character sheets:
Screenshot 2024-03-16 at 14 44 27

That screenshot shows a monster sheet? The monster sheets should be unchanged:
Screenshot 2024-03-16 at 14 46 33

**Comment by d20an** [comment]
These Changes are for the new DND5e character sheets:
Screenshot 2024-03-16 at 14 48 20

Monster sheets (as per your screenshot) should be unchanged:
Screenshot 2024-03-16 at 14 49 03

**Comment by d20an** [comment]
@jrbuda looks like maybe you've only edited two files? You shouldn't need to faff with editing the files manually – Rather than editing them, download the module from my branch and swap it in.

**Comment by eastcw** [comment]
This was a solid start, thanks. I've changed it a bit to make sure that it's still hopefully properly compatible with legacy and third-party character sheets. Once released this should fix #10, #12, and #13.

**Comment by d20an** [comment]
@eastcw thanks! Really appreciate this module, by the way. We all roll real dice, so seeing the to-hit bonus and damage rolls neatly on one pane is super useful; it's really made the difference in getting my players to get on board with using Foundry for character sheets.

**Pull request merged**
